source 'https://rubygems.org'
source 'https://rails-assets.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

################################
# My custom Gems               #
################################

gem "hist"


################################
#  TEMPORARY                   #
################################

gem 'therubyracer'

################################
# My custom Gems               #
################################

gem "hist"


################################
# Preconfigured Community Gems #
################################

gem 'select2-rails', github: 'scande3/select2-rails' # Custom version that patches in support for modals better...

gem 'ace-rails-ap'

# Font Awesome support
gem 'font_awesome5_rails', '0.4.3' # Upgrading to 0.5.0 and above causes issues in Safari?

# Jquery support
gem 'jquery-rails'

# Bootstrap 4 support
# gem 'bootstrap'

# Blacklight stuff
gem "blacklight_advanced_search"
gem "blacklight", "~> 6.19.2"
gem "blacklight-gallery", '0.11.0'
gem "blacklight_range_limit", '6.3.3'
gem "blacklight-maps", github: 'projectblacklight/blacklight-maps'
# End Blacklight

# Onmount supported Asset source
gem "rails-assets-onmount"

# Authentication dependencies
gem "devise"
gem "devise-remote-user"

# Background jobs
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'sidekiq-unique-jobs'
gem 'sidekiq-statistic', github: 'davydovanton/sidekiq-statistic'
gem 'tilt' # Required for sidekiq-statistic

###########################
# Standard Rails New Gems #
###########################
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '{{cookiecutter.rails_full_version}}'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '1.3.13'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', '< 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  gem "vcr"
  gem "webmock"
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'

  gem 'simplecov', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
